### PR TITLE
[Fix] Removed the "all rights reserved" text from the footer

### LINKED ISSUE #7: Blog is open source
Please remove the "All Rights reserved text" in the footer

### PR DESCRIPTION
**Pull request by mildrette**
Removed the all right reserved text on footer.

### CODE REVIEW

**Comment by PromiseFru** [comment]
Thank you, @mildrette. Please link the PR to the issue number in the description. Refer to the link below for more insights: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Also, please edit the PR title to reflect the change, for instance, `[Fix] Removed the "all rights reserved" text from the footer.`

File: src/app/_components/footer.tsx [hunk 1]
```diff
@@ -36,9 +36,7 @@ export function Footer() {
 				<div className="text-center mt-5">
 					<hr className="border-t-2 border-gray-400" />
 					<p className="text-sm text-gray-400 mt-3">
-						<span className="mr-2">
-							&copy; {currentYear} SMSWithoutBorders. All rights reserved.
-						</span>
+						<span className="mr-2">&copy; {currentYear} SMSWithoutBorders.</span>
```
Comment (PromiseFru) [inline src/app/_components/footer.tsx]: We can safely remove `className="mr-2"`, as it is not being used.

```suggestion
						<span>&copy; {currentYear} SMSWithoutBorders.</span>
```

File: yarn.lock
Comment (PromiseFru) [inline yarn.lock:1]: We shouldn't have a `yarn.lock` file since we're using the `pnpm` package manager instead of `yarn`.

P.S: Avoid mixing package managers as it can create unexpected behaviors.

**Review by PromiseFru — CHANGES_REQUESTED** [review]
Thank you, @mildrette! Please see my comments.

**Comment by mildrette** [comment]
@PromiseFru  all good, I fixed the issues

File: yarn.lock
Comment (PromiseFru) [inline yarn.lock:1]: Please delete the `yarn.lock` file.

**Review by PromiseFru — CHANGES_REQUESTED** [review]

File: yarn.lock
Comment (mildrette) [reply yarn.lock:1]: removed the yarn.lock file

**Review by PromiseFru — APPROVED** [review]
Thank you @mildrette!
